# Generated by Django 5.2 on 2025-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
