# Generated by Django 5.2 on 2025-11-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_order_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=20),
        ),
    ]
